// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaL0h07zzd2iQGTz0sBxnjDdOzDTx78zA',
    appId: '1:748187352181:web:4c081b7be2296ab74a4c3c',
    messagingSenderId: '748187352181',
    projectId: 'kitap-takas-firebase-6fe9b',
    authDomain: 'kitap-takas-firebase-6fe9b.firebaseapp.com',
    storageBucket: 'kitap-takas-firebase-6fe9b.firebasestorage.app',
    measurementId: 'G-JE3HTHRQ6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgnLPTvpow8WYTt5bGQLjPb7tX3qOxNSo',
    appId: '1:748187352181:android:44497f438894da874a4c3c',
    messagingSenderId: '748187352181',
    projectId: 'kitap-takas-firebase-6fe9b',
    storageBucket: 'kitap-takas-firebase-6fe9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLGXPhcpuea4jXuQWIPua6YqmuMuJitjc',
    appId: '1:748187352181:ios:bc523bd8d808fa924a4c3c',
    messagingSenderId: '748187352181',
    projectId: 'kitap-takas-firebase-6fe9b',
    storageBucket: 'kitap-takas-firebase-6fe9b.firebasestorage.app',
    iosBundleId: 'com.example.kitapTakasFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLGXPhcpuea4jXuQWIPua6YqmuMuJitjc',
    appId: '1:748187352181:ios:bc523bd8d808fa924a4c3c',
    messagingSenderId: '748187352181',
    projectId: 'kitap-takas-firebase-6fe9b',
    storageBucket: 'kitap-takas-firebase-6fe9b.firebasestorage.app',
    iosBundleId: 'com.example.kitapTakasFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaL0h07zzd2iQGTz0sBxnjDdOzDTx78zA',
    appId: '1:748187352181:web:0cd4a435ba9036e84a4c3c',
    messagingSenderId: '748187352181',
    projectId: 'kitap-takas-firebase-6fe9b',
    authDomain: 'kitap-takas-firebase-6fe9b.firebaseapp.com',
    storageBucket: 'kitap-takas-firebase-6fe9b.firebasestorage.app',
    measurementId: 'G-FK9WJMP3MZ',
  );
}
